CREATE DATABASE DB_CRYPT;

DROP TABLE IF EXISTS DB_CRYPT.ENCRYPT;

CREATE TABLE IF NOT EXISTS DB_CRYPT.encrypt
(
    ID  DECIMAL(38)  NOT NULL,
    FIO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO DB_CRYPT.encrypt (ID, FIO)
VALUES (0, 'Tds Testovy');
INSERT INTO DB_CRYPT.encrypt (ID, FIO)
VALUES (1, 'Test Testov');
INSERT INTO DB_CRYPT.encrypt (ID, FIO)
VALUES (2, 'Tom Cat');
SELECT * FROM DB_CRYPT.encrypt;